use gstreamer::prelude::*;
use gstreamer_webrtc::{WebRTCSDPType, WebRTCSessionDescription};
use std::error::Error;
use tokio::sync::mpsc;
use tracing::{info, warn, error};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
#[serde(tag = "type")]
pub enum WebrtcMessage {
    #[serde(rename = "sdp")]
    Sdp { sdp: String, is_offer: bool },
    #[serde(rename = "ice")]
    Ice { sdp_mline_index: u32, candidate: String },
}

pub async fn start_host_pipeline(
    mut sig_rx: mpsc::Receiver<String>,
    sig_tx: mpsc::Sender<String>,
) -> Result<(), Box<dyn Error>> {
    info!("Starting GStreamer WebRTC Host pipeline...");

    // Using videotestsrc for cross-platform compatibility out of the box. 
    // In production, replace with: 
    // Windows: dxgiscreencapsrc
    // macOS: avfvideosrc capture-screen=true
    // Linux: ximagesrc
    let pipeline_str = "videotestsrc is-live=true pattern=ball ! video/x-raw,width=1280,height=720,framerate=30/1 ! videoconvert ! x264enc tune=zerolatency bitrate=2000 speed-preset=ultrafast ! rtph264pay ! application/x-rtp,media=video,encoding-name=H264,payload=96 ! webrtcbin name=webrtc";
    
    let pipeline = gstreamer::parse::launch(pipeline_str)?
        .dynamic_cast::<gstreamer::Pipeline>()
        .map_err(|_| "Failed to cast to Pipeline")?;

    let webrtc = pipeline.by_name("webrtc").expect("webrtcbin not found");

    let rt = tokio::runtime::Handle::current();

    // Handle ICE candidates generated by webrtcbin
    let sig_tx_ice = sig_tx.clone();
    let rt_ice = rt.clone();
    webrtc.connect("on-ice-candidate", false, move |values| {
        let mlineindex = values[1].get::<u32>().unwrap();
        let candidate = values[2].get::<String>().unwrap();
        
        let msg = WebrtcMessage::Ice {
            sdp_mline_index: mlineindex,
            candidate,
        };
        
        if let Ok(json) = serde_json::to_string(&msg) {
            let tx = sig_tx_ice.clone();
            rt_ice.spawn(async move {
                let _ = tx.send(json).await;
            });
        }
        None
    });

    pipeline.set_state(gstreamer::State::Playing)?;

    // Listen for signaling messages from the Viewer
    let webrtc_clone = webrtc.clone();
    tokio::spawn(async move {
        while let Some(msg) = sig_rx.recv().await {
            match serde_json::from_str::<WebrtcMessage>(&msg) {
                Ok(WebrtcMessage::Sdp { sdp, is_offer: _ }) => {
                    info!("Received SDP answer from Viewer");
                    if let Ok(desc) = gstreamer_sdp::SDPMessage::parse_buffer(sdp.as_bytes()) {
                        let webrtc_sdp = WebRTCSessionDescription::new(WebRTCSDPType::Answer, desc);
                        webrtc_clone.emit_by_name::<()>("set-remote-description", &[&webrtc_sdp, &None::<gstreamer::Promise>]);
                    }
                }
                Ok(WebrtcMessage::Ice { sdp_mline_index, candidate }) => {
                    info!("Received ICE candidate from Viewer");
                    webrtc_clone.emit_by_name::<()>("add-ice-candidate", &[&sdp_mline_index, &candidate]);
                }
                Err(e) => {
                    error!("Failed to parse WebRTC message: {}", e);
                }
            }
        }
    });

    // Create an offer to send to the Viewer
    let sig_tx_offer = sig_tx.clone();
    let webrtc_offer = webrtc.clone();
    let rt_offer = rt.clone();
    let promise = gstreamer::Promise::with_change_func(move |reply| {
        let reply = match reply {
            Ok(Some(reply)) => reply,
            _ => return,
        };
        
        if let Ok(offer) = reply.get::<WebRTCSessionDescription>("offer") {
            webrtc_offer.emit_by_name::<()>("set-local-description", &[&offer, &None::<gstreamer::Promise>]);
            
            let sdp_text = offer.sdp().as_text().unwrap_or_default();
            let msg = WebrtcMessage::Sdp {
                sdp: sdp_text,
                is_offer: true,
            };
            
            if let Ok(json) = serde_json::to_string(&msg) {
                let tx = sig_tx_offer.clone();
                rt_offer.spawn(async move {
                    let _ = tx.send(json).await;
                });
            }
        }
    });

    webrtc.emit_by_name::<()>("create-offer", &[&None::<gstreamer::Structure>, &promise]);

    Ok(())
}

pub async fn start_viewer_pipeline(
    mut sig_rx: mpsc::Receiver<String>,
    sig_tx: mpsc::Sender<String>,
) -> Result<(), Box<dyn Error>> {
    info!("Starting GStreamer WebRTC Viewer pipeline...");

    let pipeline_str = "webrtcbin name=webrtc ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert ! autovideosink";
    
    let pipeline = gstreamer::parse::launch(pipeline_str)?
        .dynamic_cast::<gstreamer::Pipeline>()
        .map_err(|_| "Failed to cast to Pipeline")?;

    let webrtc = pipeline.by_name("webrtc").expect("webrtcbin not found");

    let rt = tokio::runtime::Handle::current();

    let sig_tx_ice = sig_tx.clone();
    let rt_ice = rt.clone();
    webrtc.connect("on-ice-candidate", false, move |values| {
        let mlineindex = values[1].get::<u32>().unwrap();
        let candidate = values[2].get::<String>().unwrap();
        
        let msg = WebrtcMessage::Ice {
            sdp_mline_index: mlineindex,
            candidate,
        };
        
        if let Ok(json) = serde_json::to_string(&msg) {
            let tx = sig_tx_ice.clone();
            rt_ice.spawn(async move {
                let _ = tx.send(json).await;
            });
        }
        None
    });

    pipeline.set_state(gstreamer::State::Playing)?;

    let webrtc_clone = webrtc.clone();
    tokio::spawn(async move {
        while let Some(msg) = sig_rx.recv().await {
            match serde_json::from_str::<WebrtcMessage>(&msg) {
                Ok(WebrtcMessage::Sdp { sdp, is_offer }) => {
                    if is_offer {
                        info!("Received SDP offer from Host");
                        if let Ok(desc) = gstreamer_sdp::SDPMessage::parse_buffer(sdp.as_bytes()) {
                            let webrtc_sdp = WebRTCSessionDescription::new(WebRTCSDPType::Offer, desc);
                            webrtc_clone.emit_by_name::<()>("set-remote-description", &[&webrtc_sdp, &None::<gstreamer::Promise>]);
                            
                            // Generate Answer
                            let sig_tx_answer = sig_tx.clone();
                            let webrtc_ans = webrtc_clone.clone();
                            let rt_ans = tokio::runtime::Handle::current();
                            let promise = gstreamer::Promise::with_change_func(move |reply| {
                                let reply = match reply {
                                    Ok(Some(reply)) => reply,
                                    _ => return,
                                };
                                
                                if let Ok(answer) = reply.get::<WebRTCSessionDescription>("answer") {
                                    webrtc_ans.emit_by_name::<()>("set-local-description", &[&answer, &None::<gstreamer::Promise>]);
                                    
                                    let sdp_text = answer.sdp().as_text().unwrap_or_default();
                                    let msg = WebrtcMessage::Sdp {
                                        sdp: sdp_text,
                                        is_offer: false,
                                    };
                                    
                                    if let Ok(json) = serde_json::to_string(&msg) {
                                        let tx = sig_tx_answer.clone();
                                        rt_ans.spawn(async move {
                                            let _ = tx.send(json).await;
                                        });
                                    }
                                }
                            });
                            webrtc_clone.emit_by_name::<()>("create-answer", &[&None::<gstreamer::Structure>, &promise]);
                        }
                    }
                }
                Ok(WebrtcMessage::Ice { sdp_mline_index, candidate }) => {
                    info!("Received ICE candidate from Host");
                    webrtc_clone.emit_by_name::<()>("add-ice-candidate", &[&sdp_mline_index, &candidate]);
                }
                Err(e) => {
                    error!("Failed to parse WebRTC message: {}", e);
                }
            }
        }
    });

    Ok(())
}
